language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- pip install .[test]
- pip install codecov
script: pytest --cov=./
after_success:
  - codecov
notifications:
  slack:
    rooms:
    - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd