language: python
python:
- '3.5'
- '3.6'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GIRAFFE_M2M_USERNAME="guest"
  - GIRAFFE_M2M_PASSWORD="admin1234"
  - GIRAFFE_M2M_URL="https://localhost:8080/inventory/json/v/1.4.1"
  - GIRAFFE_ARD_ES_HOST="localhost"
  - GIRAFFE_ARD_ES_INDEX="ard-tiles"
  - GIRAFFE_IWDS_URL="http://localhost:5656"
  - GIRAFFE_IWDS_ES_HOST="localhost"
  - GIRAFFE_IWDS_ES_INDEX="iwds-tifs"
install:
- pip install --upgrade pip
- pip install .[test]
- pip install codecov
script: pytest --cov=./
after_success:
  - codecov
deploy:
  - provider: script
    script: make all
    on:
      repo: USGS-EROS/lcmap-giraffe
      branch: master
      tags: false
  - provider: script
    script: make all
    on:
      repo: USGS-EROS/lcmap-giraffe
      branch: develop
      tags: false
notifications:
  slack:
    rooms:
    - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
