{
 "title": "TIFs Ingested",
 "tags": [ "templated" ],
 "time": { "from": "1980-01-01T06:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TileID",
    "query": "{\"find\": \"terms\", \"field\": \"tileid.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Archive ARD Tiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sensor.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "date_acquired", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tileid:$TileID",
     "timeField": "date_acquired"
    }
   ]
  },
  {
   "title": "Source TIFs Ingested",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sensor.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "date_acquired", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tileid:$TileID",
     "timeField": "date_acquired"
    }
   ]
  },
  {
   "title": "Missing TIF Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sensor.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "date_acquired", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(tileid:$TileID AND -_exists_:http_date)",
     "timeField": "date_acquired"
    }
   ]
  },
  {
   "title": "TIFs Ingested",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "http_date"
    }
   ]
  },
  {
   "title": "Missing TIFs",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tileid:$TileID and -_exists_:http_date",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IWDS TIFs Available",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sensor.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "region.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tile_h.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tile_v.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "layer.keyword",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "collection.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tileid:$TileID",
     "timeField": "http_date"
    }
   ]
  }
 ]
}