version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    container_name: elastic
    environment:
      - cluster.name=mynewclustername
      - bootstrap.memory_lock=true  # Avoid swap
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
    ulimits: # Avoid swap
      memlock:
        soft: -1
        hard: -1
    user: ${UID:-1000}
    volumes: []
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  dashboard:
    image: grafana/grafana:5.0.0-beta1
    container_name: dashboard
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
      GF_INSTALL_PLUGINS: >
        grafana-simple-json-datasource,grafana-piechart-panel,
        mtanda-histogram-panel,mtanda-heatmap-epoch-panel,
        neocat-cal-heatmap-panel
      GF_SERVER_ROUTER_LOGGING: "true"
      #GF_SECURITY_DATA_SOURCE_PROXY_WHITELIST: "localhost:9200"
      #GF_AUTH_PROXY_ENABLED: "true"
      GF_PLUGIN_JSON_ANNOTATIONS: "true"
      # GF_SESSION_COOKIE_SECURE: "true" -- redirects too many times?
    volumes: []
      # - data-grafana:/var/lib/grafana
