version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    container_name: elastic
    environment:
      - cluster.name=mynewclustername
      - bootstrap.memory_lock=true  # Avoid swap
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
    ulimits: # Avoid swap
      memlock:
        soft: -1
        hard: -1
    user: ${UID:-1000}
    volumes: []
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
