version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    container_name: elastic
    environment:
      - cluster.name=mynewclustername
      - bootstrap.memory_lock=true  # Avoid swap
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
      - http.host=0.0.0.0
    ulimits: # Avoid swap
      memlock:
        soft: -1
        hard: -1
    user: ${UID:-1000}
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9200
    networks:
      - lcmap_giraffe
  dashboard:
    image: grafana/grafana:5.0.0-beta1
    container_name: dashboard
    ports:
      - "127.0.0.1:3000:3000"
    environment: []
    volumes:
       - grafana1:/var/lib/grafana
       - ./grafana:/etc/grafana
       - /etc/localtime:/etc/localtime:ro
       - ./grafana/plugins:/var/lib/grafana/plugins
    networks:
      - lcmap_giraffe

volumes:
  esdata1:
  grafana1:

networks:
  lcmap_giraffe:
    driver: bridge
